config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'prototypes#index'

  resources :users, only: [:edit, :update, :show]
  resources :prototypes

  scope module: :prototypes do
    resources :popular, only: :index
    resources :newest, only: :index
    resources :comments, only: :create
    resources :likes, only: [:create, :destroy]
    resources :tags, only: :index do
      collection do
        get ':tag_name' => 'tags#show'
      end
    end
  end
end

app/models/captured_image.rb
class CapturedImage < ActiveRecord::Base
  mount_uploader :content, ImageUploader

  enum status: %i(main sub)

  belongs_to :prototype

  validates :content,
            :status,
            presence: true,
            on: :create

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :user
  belongs_to :prototype
end

app/models/like.rb
class Like < ActiveRecord::Base
  belongs_to :user
  belongs_to :prototype, counter_cache: :likes_count
end

app/models/prototype.rb
class Prototype < ActiveRecord::Base
  belongs_to :user
  has_many :captured_images, dependent: :delete_all
  has_many :comments, dependent: :delete_all
  has_many :likes, dependent: :delete_all

  accepts_nested_attributes_for :captured_images, reject_if: :reject_sub_images

  acts_as_taggable
  acts_as_ordered_taggable
  paginates_per 8

  validates :title,
            :catch_copy,
            :concept,
            presence: true,
            on: :create

  def reject_sub_images(attributed)
    attributed['content'].blank?
  end

  def set_main_thumbnail
    captured_images.main.first.content
  end

  def set_sub_thumbnail(i)
    captured_images.sub[i].present? ? captured_images.sub[i].content : ActionController::Base.helpers.asset_path('noimage.png')
  end

  def user_position
    postion = if user.position.present?
      user.position
    else
      "- No Data - "
    end
  end

  def posted_date
    created_at.strftime('%b %d %a')
  end

  def fetch_curret_user_like(user)
    likes.find_by(user_id: user)
  end

  def fetch_tag(i)
    if tag_list[i].present?
      tag_list[i]
    else
      ""
    end
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  mount_uploader :avatar, ImageUploader

  has_many :prototypes
  has_many :comments
  has_many :likes

  validates :name,
            presence: true,
            on: :create

  def set_profile_photo
    avatar.present? ? avatar : ActionController::Base.helpers.asset_path('noimage.png')
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up).push(:name, :profile, :position, :occupation, :avatar)
    devise_parameter_sanitizer.for(:account_update).push(:name, :profile, :position, :occupation, :avatar)
  end

  def after_sign_out_path_for(resource)
    new_user_session_path
  end
end

app/controllers/prototypes/comments_controller.rb
class Prototypes::CommentsController < ApplicationController
  before_action :set_prototype, only: :create

  def create
    @prototype.comments.create(comment_params)
  end

  private
  def set_prototype
    @prototype = Prototype.find(params[:comment][:prototype_id])
  end

  def comment_params
    params.require(:comment).permit(
      :user_id,
      :content
    )
  end
end

app/controllers/prototypes/likes_controller.rb
class Prototypes::LikesController < ApplicationController
  before_action :set_prototype, only: :create

  def create
    @prototype.likes.create(params.permit(:user_id))
  end

  def destroy
    Like.find(params[:id]).destroy
    @prototype = Prototype.eager_load(:comments, { comments: :user }).find(params[:prototype_id])
  end

  private
  def set_prototype
    @prototype = Prototype.eager_load(:comments, { comments: :user }).find(params[:prototype_id])
  end
end

app/controllers/prototypes/newest_controller.rb
class Prototypes::NewestController < ApplicationController
  def index
    @prototypes = Prototype.order(created_at: :desc).page(params[:page])
    render template: "prototypes/index"
  end
end

app/controllers/prototypes/popular_controller.rb
class Prototypes::PopularController < ApplicationController
  def index
    @prototypes = Prototype.order(likes_count: :desc).page(params[:page])
    render template: "prototypes/index"
  end
end

app/controllers/prototypes/tags_controller.rb
class Prototypes::TagsController < ApplicationController
  def index
    total = ActsAsTaggableOn::Tag.all.count
    @tags = ActsAsTaggableOn::Tag.most_used(total)
  end

  def show
    @tag = ActsAsTaggableOn::Tag.find_by(name: params[:tag_name])
    @prototypes = Prototype.tagged_with(params[:tag_name])
  end
end

app/controllers/prototypes_controller.rb
class PrototypesController < ApplicationController
  before_action :set_prototype, only: [:edit, :destroy, :update]
  before_action :set_new_comment, only: [:show, :update]

  def index
    @prototypes = Prototype.order("RAND()").page(params[:page])
  end

  def new
    @prototype = Prototype.new
    @prototype.captured_images.build
  end

  def show
    @prototype = Prototype.eager_load(:comments, { comments: :user }).find(params[:id])
    @likes = @prototype.likes
  end

  def edit
  end

  def create
    prototype = Prototype.new(prototype_params)
    if prototype.save
      redirect_to :root, notice: 'The new prototype was successfully created'
    else
      redirect_to action: :new, notice: 'The new prototype was unsuccessfully created'
    end
  end

  def destroy
    if @prototype.destroy
      redirect_to :root, notice: 'Your prototype was successfully deleted'
    else
      render action: :show, notice: 'Your prototype was unsuccessfully deleted'
    end
  end


  def update
    if @prototype.update(prototype_params)
      render action: :show, notice: 'Your prototype was successfully updated'
    else
      render action: :edit, notice: 'Your prototype was unsuccessfully updated'
    end
  end

  private
  def set_prototype
    @prototype = Prototype.find(params[:id])
  end

  def set_new_comment
    @comment = Comment.new
  end

  def prototype_params
    tag_list = params[:prototype][:tag_list]
    params.require(:prototype).permit(
      :title,
      :catch_copy,
      :concept,
      :user_id,
      :tag_list,
      captured_images_attributes: [:content, :status, :id]
    ).merge(tag_list: tag_list)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :update, :edit]

  def show
    @prototypes = @user.prototypes.page(params[:page])
  end

  def update
    @user.update(user_params)
    redirect_to :root, notice: 'The user information was successfully updated'
  end

  def edit
  end

  private
  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(
      :name,
      :email,
      :position,
      :profile,
      :occupation,
      :avatar
    )
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/common/_footer.html.haml
.container
  %footer
    %p &copy; PROTO SPACE 2015.
  

app/views/common/_header.html.haml
.navbar.navbar-default.navbar-static-top.navbar-fixed-top
  .container
    %button.navbar-toggle(type="button" data-toggle="collapse" data-target=".navbar-responsive-collapse")
      %span.icon-bar
      %span.icon-bar
      %span.icon-bar
    .navbar-brand
      = link_to image_tag("logo.png", alt: "PROTO TYPE - SHARE THE PROTOTYPE", height: "36px"), root_path
    .navbar-collapse.collapse.navbar-responsive-collapse
      - if user_signed_in?
        %ul.nav.navbar-nav.navbar-right
          %li.dropdown
            = link_to "#", class: 'dropdown-toggle', role: 'button', 'aria-expanded' =>  'false', 'data-toggle' => 'dropdown' do
              #{current_user.name}
              %span.caret
            %ul.dropdown-menu{role: "menu"}
              %li
                = link_to 'My Page', user_path(current_user)
              %li
                = link_to 'Edit Profile', edit_user_path(current_user)
              %li
                = link_to 'Logout', destroy_user_session_path, method: :delete
          %li
            .btn.btn-default.navbar-btn
              = link_to "New Photo", new_prototype_path
      - else
        %ul.nav.navbar-nav.navbar-right
          %li
            .btn.btn-default.navbar-btn
              = link_to 'Get Started', new_user_session_path

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Protospace
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body
    %header
      = render partial: 'common/header'

    - if alert
      .p.alert.alert-dander
        = alert

    - if flash[:notice]
      .p.alert.alert-success
        = flash[:notice]

    = yield
    %footer
      = render partial: 'common/footer'

app/views/prototypes/_comment.html.haml
.media
  .media-left
    - if comment.user.avatar.present?
      = link_to image_tag(comment.user.avatar, class: "user-icon"), user_path(comment.user)
    - else
      = image_tag("noimage.png", alt: "No image", data: { holder: { rendered: true }, src: "holder.js/64x64" }, class: "user-icon")

  .media-body
    %h4#top-aligned-media.media-heading
      = comment.user.name
      %a.anchorjs-link{href: "#top-aligned-media"}
        %span.anchorjs-icon
    %p
      = comment.content

app/views/prototypes/_like.html.haml
- if user_signed_in?
  - if prototype.fetch_curret_user_like(current_user)
    = button_to like_path(id: prototype.fetch_curret_user_like(current_user), user_id: current_user, prototype_id: prototype), method: :delete, remote: true, class: 'btn btn-default btn-like' do
      = image_tag("icon_heart_red.svg")
      Like
      %span#likes_number.num
        = prototype.likes_count

  -else
    = button_to likes_path(user_id: current_user, prototype_id: prototype), method: :post, remote: true, class: 'btn btn-default btn-like' do
      = image_tag("icon_heart.svg")
      Like
      %span#likes_number.num
        = prototype.likes_count

- else
  %button.btn.btn-default.btn-like
    = image_tag("icon_heart_red.svg")
    Like
    %span#likes_number.num
      = prototype.likes_count

app/views/prototypes/_prototype.html.haml
.col-sm-4.col-md-3.proto-content
  .thumbnail
    = link_to image_tag(prototype.set_main_thumbnail), prototype_path(prototype)
    .caption
      %h3
        = prototype.title
      .proto-meta
        .proto-user
          = link_to prototype.user.name, user_path(prototype.user)
        .proto-posted
          = prototype.posted_date
      -# %ul.proto-tag-list.list-inline
      -#   %li
      -#     %a{:href => "#", :class => "btn btn-default"} iPad
      -#   %li
      -#     %a{:href => "#", :class => "btn btn-default"} wireframe

app/views/prototypes/comments/create.js.haml
$('#comments_number').text('(#{ @prototype.comments.size })');
$('#comment-field').val('');
:plain
  $('#comments').html(
    '#{ j render partial: 'prototypes/comment', collection: @prototype.comments }'
  );

app/views/prototypes/edit.html.haml
.container.proto-new
  = form_for @prototype, url: { action: :update, id: @prototype } do |f|
    = f.hidden_field :user_id, value: current_user.id
    .col-md-8.col-md-offset-2
      %header.row.user-nav.row
        .col-md-12
          %h4 Title
          .proto-new-title
            = f.text_field :title, required: true, autofocus: true, placeholder: "Input Title"
      .row
        .col-md-12
          %h4 Main Thumbnail
          .cover-image-upload{ style: "background: url(#{@prototype.set_main_thumbnail}) no-repeat center center; background-size: contain;" }
            = f.fields_for :captured_images, @prototype.captured_images.main do |image|
              = image.file_field :content
              = image.hidden_field :status, value: "main"

          %h4 Sub Thumbnails
          %ul.proto-sub-list.list-group
            - 3.times do |i|
              = f.fields_for :captured_images, @prototype.captured_images.sub[i] do |image|
                - if image.index <= 3
                  %li.list-group-item.col-md-4
                    .image-upload{ id: "sub_image_#{i}_uploader", style: "background: url(#{@prototype.set_sub_thumbnail(i)}) no-repeat center center;" }
                      %img{ src: "" }
                      = image.file_field :content
                      = image.hidden_field :status, value: "sub"
                      - if @prototype.captured_images.sub[i].blank?
                        = image.hidden_field :id, value: ""

      .row.proto-description
        .col-md-12
          %h4 Catch Copy
          = f.text_field :catch_copy, require: true, placeholder: "Input Catch Copy"
        .col-md-12
          %h4 Concept
          = f.text_area :concept, require: true, placeholder: "Input Concept"
        -# .col-md-12
        -#   %h4 Tag List
        -#   .row
        -#     .col-md-3
        -#       %input{:type => "text", :placeholder => "Web Design"}/
        -#     .col-md-3
        -#       %input{:type => "text", :placeholder => "UI"}/
        -#     .col-md-3
        -#       %input{:type => "text", :placeholder => "Application"}/
        .col-md-12
          %h4 Tag List
          .row
            - 3.times do |i|
              .col-md-3
                = text_field_tag "prototype[tag_list][]", @prototype.fetch_tag(i)
      .row.text-center.proto-btn
        = f.submit "UPDATE", id: "button", class: "btn btn-lg btn-primary btn-block"

app/views/prototypes/index.html.haml
.jumbotron
  .container.text-center
    = image_tag("header_logo.png", alt: "PROTO TYPE - SHARE THE PROTOTYPE", height: "73px")

.filter-nav
  .container
    .row
      %ul.nav.nav-pills.col-lg-11
        %li.btn-default.btn-popular
          = link_to "Popular", popular_index_path
        %li.btn-default.btn-popular
          = link_to "Newest", newest_index_path
      = link_to "VIEW TAGS", tags_path, class: "btn btn-default col-lg-1"

.container.proto-list
  .row
    = render partial: 'prototypes/prototype', collection: @prototypes

.text-center
  %ul.pagination
    = paginate @prototypes

app/views/prototypes/likes/create.js.haml
:plain
  $('#like').html(
    '#{ j render partial: 'prototypes/like', locals: { prototype: @prototype }  }'
  );

app/views/prototypes/likes/destroy.js.haml
:plain
  $('#like').html(
    '#{ j render partial: 'prototypes/like', locals: { prototype: @prototype }  }'
  );

app/views/prototypes/new.html.haml
.container.proto-new
  = form_for @prototype do |f|
    = f.hidden_field :user_id, value: current_user.id
    .col-md-8.col-md-offset-2
      %header.row.user-nav.row
        .col-md-12
          %h4 Title
          .proto-new-title
            = f.text_field :title, required: true, autofocus: true, placeholder: "Input Title"
      .row
        .col-md-12
          %h4 Main Thumbnail
          .cover-image-upload#main_image_uploader
            = f.fields_for :captured_images do |image|
              %img{src: ""}
              = image.file_field :content, required: true
              = image.hidden_field :status, value: "main"
        .col-md-12
          %h4 Sub Thumbnails
          %ul.proto-sub-list.list-group
            - 3.times do |i|
              %li.list-group-item.col-md-4
                .image-upload{ id: "sub_image_#{i}_uploader" }
                  = f.fields_for :captured_images do |image|
                    %img{src: ""}
                    = image.file_field :content
                    = image.hidden_field :status, value: "sub"
      .row.proto-description
        .col-md-12
          %h4 Catch Copy
          = f.text_field :catch_copy, require: true, placeholder: "Input Catch Copy"
        .col-md-12
          %h4 Concept
          = f.text_area :concept, require: true, placeholder: "Input Concept"
        .col-md-12
          %h4 Tag List
          .row
          - %w(UI/UX Ruby Application).each do |val|
            .col-md-3
              = text_field_tag "prototype[tag_list][]", "", placeholder: val
      .row.text-center.proto-btn
        = f.submit "PUBLISH", id: "button", class: "btn btn-lg btn-primary btn-block"

app/views/prototypes/show.html.haml
.container.proto-page
  %header.row.user-nav
    .col-md-6
      .media
        .media-left
          - if @prototype.user.avatar.present?
            = link_to image_tag(@prototype.user.avatar, class: "user-icon"), user_path(@prototype.user)
          - else
            = image_tag("noimage.png", alt: "No image", data: { holder: { rendered: true }, src: "holder.js/64x64" }, class: "media-object", style: "width: 64px; height: 64px;")
        .media-body
          %h4#top-aligned-media.media-heading
            = @prototype.title
          .proto-user
            by
            = link_to "#{@prototype.user.name}", user_path(@prototype.user)
            .degree
              = @prototype.user_position

    .col-md-6#like.text-right
      = render partial: 'prototypes/like', locals: { prototype: @prototype }
    .col-md-6.text-right
      .extra-button
        - if user_signed_in? && @prototype.user_id == current_user.id
          .btn.btn-default.navbar-btn
            = link_to "Edit", edit_prototype_path(@prototype)
          .btn.btn-default.navbar-btn
            = link_to "Delete", prototype_path(@prototype), method: :delete

  .row
    .col-md-9.image-box
      = image_tag @prototype.set_main_thumbnail, class: 'img-responsive img-size-fix'
    .col-md-3
      %ul.proto-sub-list.list-group
        - @prototype.captured_images.sub.each do |image|
          %li.list-group-item
            = image_tag(image.content, class: 'img-responsive')
  .row.proto-description
    .col-md-3
      %h4 Catch Copy
      %p
        = @prototype.catch_copy
    .col-md-6
      %h4 Concept
      %p
        = @prototype.concept
    .col-md-3
      %h4 Tag List
      %ul.proto-tag-list.list-inline
        - @prototype.tag_list.each do |val|
          %li
            = link_to val, ({ controller: "prototypes/tags", action: :show, tag_name: val }), class: "btn btn-default"
    %h4.col-md-12
      Comments
      %span#comments_number.num  (#{@prototype.comments.size})
    .col-md-8
      #comments
        = render partial: 'prototypes/comment', collection: @prototype.comments
      %form.form-inline
      - if user_signed_in?
        = form_for @comment, remote: true do |f|
          = f.hidden_field :user_id, value: current_user.id
          = f.hidden_field :prototype_id, value: @prototype.id
          %h4 Write a comment
          .row
            .form-group.col-md-10
              = f.text_area :content, require: true, rows: "3", placeholder: "Your comments", id: "comment-field", class: "form-control"
            .form-group.col-md-2
              = f.submit "COMMENT", class: "button btn btn-primary"

app/views/prototypes/tags/index.html.haml
.container.tag-list.clearfix
  .row
    - @tags.each do |tag|
      .col-sm-4.col-sm-3.tag-content
        .thumbnail
          = link_to "#{tag.name}", ({ action: :show, tag_name: tag.name }), class: "tag-name btn btn-default"
          = link_to "#{tag.taggings.count} Projects", ({ action: :show, tag_name: tag.name }), class: "tag-project-number label label-default"

app/views/prototypes/tags/show.html.haml
.jumbotron
  .container.text-center
    = image_tag("header_logo.png", alt: "PROTO TYPE - SHARE THE PROTOTYPE", height: "73px")

.filter-nav
  .container
    .row
      %ul.nav.nav-pills.col-lg-11
        %li.active{role: "presentation"}
          = link_to "Popular PROTO", popular_index_path
        %li{role: "presentation"}
          = link_to "Newest PROTO", newest_index_path
      = link_to "VIEW TAGS", tags_path, class: "btn btn-default col-lg-1"

.container.proto-list.tag-list
  .row
    .col.sm-12.tag-content
      .thumbnail
        = link_to "#{@tag.name}", ({ action: :show, tag_name: @tag.name }), class: "tag-name btn btn-default"
        = link_to "#{@tag.taggings.count} Projects", ({ action: :show, tag_name: @tag.name }), class: "tag-project-number label label-default"

    = render partial: 'prototypes/prototype', collection: @prototypes

app/views/users/edit.html.haml
.container.user-new.clearfix
  = form_for @user do |f|
    .col-md-8.col-md-offset-2
      %header.row.user-nav.row
        .col-md-12
          %h2 Edit
          .user-name_image.row
            .user-name.col-md-10
              = f.text_field :name, placeholder: "Input Username", autofocus: true, required: true
            .user-image.col-md-2
              %img{ style: "background: url(#{@user.set_profile_photo}) no-repeat center center; background-size: cover;" }
              = f.file_field :avatar
          .user-email
            = f.text_field :email, placeholder: "Input Email", required: true
        .col-md-12
          %h4 Position
          .user-user-member.row
            .user-name.col-md-12
              = f.text_field :position, placeholder: "Input Position"
          %h4 Profile
          .user-user-profile.row
            .user-name.col-md-12
              = f.text_area :profile, placeholder: "Input Profile", size:"30×4"
          %h4 Occupation
          .user-name_image.row
            .user-name.col-md-12
              = f.text_area :occupation, placeholder: "Input Occupation", size: "30×4"
        .row.text-center.user-btn
          .actions
            = f.submit "SAVE", id: "button", class: "btn btn-lg btn-primary btn-block"

app/views/users/show.html.haml
.jumbotron
  .container.text-center
    = image_tag("header_logo.png", alt: "PROTO TYPE - SHARE THE PROTOTYPE", height: "73px")

.filter-nav
  .container
    .row
      %ul.nav.nav-pills.col-lg-11
        %li.btn-default.btn-popular
          = link_to "Popular", popular_index_path
        %li.btn-default.btn-popular
          = link_to "Newest", newest_index_path
      = link_to "VIEW TAGS", tags_path, class: "btn btn-default col-lg-1"

.container.proto-list
  .row
    = render partial: 'prototypes/prototype', collection: @prototypes

.text-center
  %ul.pagination
    = paginate @prototypes